---
- name: Ensure system directory exists
  become: yes
  become_user: root
  file: path=/usr/lib/systemd/system state=directory
- name: install systemd service
  become: yes
  become_user: root
  register: consul_service_modified
  with_items:
    usr/lib/systemd/system/consul.service
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: consul_service_modified|changed
  command: systemctl daemon-reload
    
- name: launch consul service
  become: yes
  become_user: root
  service: name=consul enabled=true state=started
